// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khdkzphobvsbgcdhwvao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoZGt6cGhvYnZzYmdjZGh3dmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzQ5MDQsImV4cCI6MjA3MjU1MDkwNH0.8e4fg4Lgq6sso9dTuI-PJoJF0GFe2Cg3qyH5ZxvKph4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});